### ISSUE TITLE
Live yet?

### ISSUE THREAD

**Issue by egermani** [bokand/URLBarSizing#8]
Hi David,

My team just so happens to be working on a site that relies on 100vh sections, and I was tasked with looking into the bug that was causing these sections to recalculate their height on mobile when Chrome's address bar slid away. So coming upon this repo was some major serendipity.

From what I can tell this fix went into Chrome 56, but my iPhone is on 56.0.2924.79, and the bug is still there. Am I missing something?

Either way, thanks for advocating for this new behavior, I think it makes a lot more sense than the current model.

**Comment by bokand** [comment]
Hey, yes it shipped in Blink in M56. However, on iPhone, Chrome doesn't use Blink since iOS disallows third-party rendering engines. Chrome uses the built in WebKit so there's major differences. That said, Safari doesn't resize the vh units so that's surprising. I'll take a look when I get to an iPhone but it sounds to me like this should be a bug filed against Chrome for iOS.

**Comment by egermani** [comment]
Oh! I didn't put it together that Chrome runs on different rendering engines depending on device. That's good to know for the future, thanks for taking the time to clarify that for me. And congrats on shipping -- I saw some timestamps back to 2014 in your bug tracker threads, that's a long road.
