### ISSUE TITLE
documentElement.clientHeight when position is fixed

### ISSUE THREAD

**Issue by sethbrenith** [bokand/URLBarSizing#9]
Hello,

First, thanks a lot for putting this page together; it's a great resource.

Second, I find that if I have `html { position:fixed }` and the URL bar is collapsed, then percentage heights adjust to the larger size and  `document.documentElement.offsetHeight` reflects the larger size, but `document.documentElement.clientHeight` is still the smaller size. To my understanding, it would make more sense for `clientHeight` to also contain the larger size. Is this effect an intentional piece of this change, or is it a bug?

(How can you get the URL bar to hide with `html { position:fixed }`, you might ask? It seems that returning from a fullscreened video always gets rid of the URL bar.)

Thanks!

**Comment by bokand** [comment]
Hey @sethbrenith! Apologies for the long delay - this slipped off my radar.

Whoa, that's definitely unintentional. I would expect `documentElement.clientHeight` to adjust to the larger size as well. It seems that this is specific to the documentElement, making body or any other element fixed does not show the same issue. I suspect there's a special case for documentElement due to it being so quirky (as you can see from [its implementation](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/Element.cpp?q=Element::clientHeight+package:%5Echromium$&l=758) )

I've filed [issue 726322](https://crbug.com/726322) in the Chromium bug tracker to fix this. Thanks for bringing it up!
